version: '3'

services:
  postgre:
    container_name: postgre_db
    image: postgres:latest
    restart: unless-stopped
    ports:
      - ${POSTGRE_PORTS}
    env_file:
      - .env
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}